const airlineCodeMap = {
        "AA":" American Airlines",
        "AF": "Air France",
        "BA": "British Airways",
        "DL": "Delta Air Lines",
        "EK": "Emirates",
        "ET": "Ethiopian Airlines",
        "KLM": "Royal Dutch Airlines",
        "LH": "Lufthansa",
        "QR": "Qatar Airways",
        "UA": "United Airlines",
        "US": "US Airways",
        "WB":" RwandAir",
        "SQ": "Singapore Airlines",
        "NH": "All Nippon Airways",
        "AF": "Air France",
        "AS": "Alaska Airlines",
        "AX": "Alaska Airlines",
        "B6": "JetBlue Airways",
        "BA": "British Airways",
        "C9": "Condor",
        "DL": "Delta Air Lines",
        "EV": "EVA Air",
        "F9": "Frontier Airlines",
        "FL": "AirTran Airways",
        "HA": "Hawaiian Airlines",
        "IA": "IAG",
        "JF": "JetBlue Airways",
        "TK": "Turkish Airlines",
        "AC": "Air Canada",
        "US": "US Airways",
        "VX": "Virgin America",
        "WN": "Southwest Airlines",
        "TW": "Turkish Airlines",
        "YV": "Vueling Airlines",
        "9E": "JetBlue Airways",
        "9N": "JetBlue Airways",
        "AA": "American Airlines",
        "AB": "Air Canada",
        "AC": "Air Canada",
        "AD": "Air France",
        "AE": "Emirates",
        "AF": "Air France",
        "AG": "Lufthansa",
        "AH": "Air New Zealand",
        "AI": "Air India",
        "AJ": "Air Japan",
        "AK": "Alaska Airlines",
        "AL": "Alitalia",
        "AM": "Air Malta",
        "AN": "Air New Zealand",
        "AO": "Air Arabia",
        "AP": "Air Philippines",
        "AQ": "Air France",
        "AR": "Air Serbia",
        "AS": "Alaska Airlines",
        "AT": "Air Transat",
        "AU": "Austrian Airlines",
        "AV": "Alitalia",
        "AW": "Air Serbia",
        "AX": "Alaska Airlines",
        "AY": "Air Serbia",
        "AZ": "Alitalia",
    };

    function getFullAirlineName(code){
        const upperCaseCode = code.toUpperCase();
        return airlineCodeMap[upperCaseCode] || code;
    }

    module.exports = {
        getFullAirlineName
    };